name: Build and Upload Release JAR

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Extract version from tag
        id: tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build with Maven using tag as version
        run: mvn clean package -Drevision=${VERSION}

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/ServerUnderDevelopment-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
